[btw] server should bind to all interfaces

diff --git a/bin/btw b/bin/btw
--- a/bin/btw
+++ b/bin/btw
@@ -21,7 +21,6 @@ IF_INDEX=1
 # in server mode or not?
 SERVER_MODE=
 
-
 usage() {
    printf 'Usage: %s [-h] [-s] [-p PORT] [-e CMD] [-i N]\n' "$0" >&2
    printf '\t-h: Display this help message and exit.\n' >&2
@@ -107,18 +106,18 @@ get_ip_address() {
    )
 
    if [ -z "$IF_IP" ] ; then
-      printf "%s: ERROR: failed to get brigde addr with index '%s'\n" "$0" "$IF_INDEX" >&2
+      printf "%s: ERROR: failed to get bridge addr with index '%s'\n" "$0" "$IF_INDEX" >&2
       exit 1
    fi
 }
 
 send_command_to_server() {
-   printf '%s\n' "$E_CMD" | nc $IF_IP $PORT
+   printf '%s\n' "$E_CMD" | nc 172.17.0.1 $PORT
 
-   if [ $? -ne 0 ] ; then
-      printf '%s: ERROR: could establish connection to server\n' "$0" >&2
-      exit 1
-   fi
+   #if [ $? -ne 0 ] ; then
+   #   printf '%s: ERROR: could establish connection to server\n' "$0" >&2
+   #   exit 1
+   #fi
 }
 
 command_executor_server() {
@@ -126,11 +125,11 @@ command_executor_server() {
    local FIFO_BUF=$(mktemp -u /tmp/btw-buf-XXXXXX) FIFO_CMD=$(mktemp -u /tmp/btw-cmd-XXXXXX)
 
    printf 'Starting the command executor server\n'
-   printf 'Listening on %s:%s\n' "$IF_IP" "$PORT"
+   printf 'Listening on 0.0.0.0:%s\n' "$PORT"
 
    mkfifo "$FIFO_BUF" "$FIFO_CMD"
 
-   cat "$FIFO_BUF" | nc -l $IF_IP $PORT | {
+   cat "$FIFO_BUF" | nc -l 0.0.0.0 $PORT | {
       while read BUF ; do
          if [ -z "$SEND_CMD" ] ; then
             printf "Executing '%s'\n" "$BUF"
@@ -147,10 +146,12 @@ command_executor_server() {
 main() {
    parse_check_args "$@"
    get_ip_address
-   if [ "$SERVER_MODE" ] ; then
+
+   if [ -n "$SERVER_MODE" ] ; then
       command_executor_server
+   else
+      send_command_to_server
    fi
-   send_command_to_server
 }
 
 main "$@"
