[btw]: fix some issues with server implementation

diff --git a/bin/btw b/bin/btw
--- a/bin/btw
+++ b/bin/btw
@@ -10,6 +10,8 @@
 # IP addr of the docker interface
 IF_IP=
 
+PORT=
+
 # command btw pipes
 E_CMD=
 
@@ -22,9 +24,10 @@ SERVER_MODE=
 usage() {
    printf 'Usage: %s [-h] [-s] [-e CMD] [-i N]\n' "$0" >&2
    printf '\t-h: Display this help message and exit.\n' >&2
-   printf '\t-s: Switch in server mode, listen to commands.\n' >&2
-   printf '\t-e: Send command "CMD" to server for executing and pour out its output.\n' >&2
-   printf '\t-i: Establish a connection to the Nth Docker brigde to listen for commands(in server mode) or send commands(in client mode).\n' >&2
+   printf '\t-s: Switch in server mode, listen to clients for commands.\n' >&2
+   printf '\t-e: Send command "CMD" to server for execution and pour out its output.\n' >&2
+   printf '\t-i: Defaults to the first brigde. Establish a connection to the Nth Docker brigde\n' >&2
+   printf '\t    to listen for commands(in server mode) or send commands(in client mode). \n' >&2
    exit 1
 }
 
@@ -50,9 +53,9 @@ parse_check_args() {
       esac
 
       IF_INDEX=${IF_INDEX:-1}
-      if [ -z "$SERVER_MODE" ] && [ -z "$E_CMD" ] then
+      if [ -z "$SERVER_MODE" ] && [ -z "$E_CMD" ] ; then
          printf '%s: ERROR: your are not in server mode\n' "$0" >&2
-         printf "%s: ERROR: use \`-e' to send command option\n" "$0" >&2
+         printf "%s: ERROR: use \`-e' option to send a command\n" "$0" >&2
          usage
       fi
    done
@@ -102,17 +105,26 @@ send_command_to_server() {
 }
 
 command_executor_server() {
-   local CMD=
-   local FIFO_FILE=$(mktemp -u /tmp/XXXXXX)
+   local CMD= SEND_CMD=
+   local FIFO_BUF=$(mktemp -u /tmp/btw-buf-XXXXXX) FIFO_CMD=$(mktemp -u /tmp/btw-cmd-XXXXXX)
 
    printf 'Starting the command executor server\n'
-   printf 'Listening to on %s:%s\n' "$IF_IP" "$PORT"
+   printf 'Listening on %s:%s\n' "$IF_IP" "$PORT"
 
-   mkfifo "$FIFO_FILE"
-   cat "$FIFO_FILE" | nc -l $IF_IP | while read COMMAND ; do
-      printf "Executing '%s'\n" "$CMD"
-      sh -c "$CMD" 2>&1 >"$FIFO_FILE"
-   done
+   mkfifo "$FIFO_BUF" "$FIFO_CMD"
+
+   cat "$FIFO_BUF" | nc -l $IF_IP | {
+      while read BUF ; do
+         if [ -z "$SEND_CMD" ] ; then
+            printf "Executing '%s'\n" "$BUF"
+            printf '%s\n' "$BUF" >"$FIFO_CMD" &
+            SEND_CMD=1
+         fi
+
+         printf '%s\n' "$BUF"
+      done
+   } | sh -c "$(cat "$FIFO_CMD")" 2>&1 >"$FIFO_BUF"
+
 }
 
 main() {
