[btw] use tail -f instead of pipes

diff --git a/bin/btw b/bin/btw
--- a/bin/btw
+++ b/bin/btw
@@ -97,7 +97,7 @@ get_ip_address() {
          }
          /inet [1-9][0-9]+(\.[1-9][0-9]+)+/ {
             if ( found_ip ) {
-               sub("/.+$", "", $2)
+               sub(" \..+/.+$", ".1", $2)
                print $2
                exit(0)
             }
@@ -106,30 +106,31 @@ get_ip_address() {
    )
 
    if [ -z "$IF_IP" ] ; then
-      printf "%s: ERROR: failed to get bridge addr with index '%s'\n" "$0" "$IF_INDEX" >&2
+      printf "%s: ERROR: failed to get bridge addr with index '%s'\n" "$0" $IF_INDEX >&2
       exit 1
    fi
 }
 
 send_command_to_server() {
-   printf '%s\n' "$E_CMD" | nc 172.17.0.1 $PORT
+   printf '%s\n' "$E_CMD" | nc "$IF_IP" $PORT
 
-   #if [ $? -ne 0 ] ; then
-   #   printf '%s: ERROR: could establish connection to server\n' "$0" >&2
-   #   exit 1
-   #fi
+   if [ $? -ne 0 ] ; then
+      printf '%s: ERROR: could establish connection to server\n' "$0" >&2
+      exit 1
+   fi
 }
 
 command_executor_server() {
    local CMD= SEND_CMD=
-   local FIFO_BUF=$(mktemp -u /tmp/btw-buf-XXXXXX) FIFO_CMD=$(mktemp -u /tmp/btw-cmd-XXXXXX)
+   local BUF_FILE=$(mktemp -u /tmp/btw-buf-XXXXXX) FIFO_CMD=$(mktemp -u /tmp/btw-cmd-XXXXXX)
 
    printf 'Starting the command executor server\n'
-   printf 'Listening on 0.0.0.0:%s\n' "$PORT"
+   printf 'Listening on %s:%s\n' "$IF_IP" $PORT
 
-   mkfifo "$FIFO_BUF" "$FIFO_CMD"
+   touch $BUF_FILE
+   mkfifo $FIFO_CMD
 
-   cat "$FIFO_BUF" | nc -l 0.0.0.0 $PORT | {
+   tail -f $BUF_FILE | nc -lk "$IF_IP" $PORT | {
       while read BUF ; do
          if [ -z "$SEND_CMD" ] ; then
             printf "Executing '%s'\n" "$BUF"
@@ -139,14 +140,14 @@ command_executor_server() {
 
          printf '%s\n' "$BUF"
       done
-   } | sh -c "$(cat "$FIFO_CMD")" 2>&1 >"$FIFO_BUF"
+   } | sh -c "$(cat "$FIFO_CMD")" 2>&1 >$BUF_FILE
 
 }
 
 main() {
    parse_check_args "$@"
-   get_ip_address
 
+   get_ip_address
    if [ -n "$SERVER_MODE" ] ; then
       command_executor_server
    else
