Update some scripts.

diff --git a/bin/record b/bin/record
--- a/bin/record
+++ b/bin/record
@@ -3,78 +3,18 @@
 # Record an X window with ffmpeg
 
 # Globals
-out_file=
 frame_rate=25
-pixel_border=0
-out_dir=
+pixel_border=2
+out_dir="$HOME/Videos/Record"
+out_file="$out_dir/$(date +'%d-%m-%y-%ss').mp4"
+pid_file="$HOME/.record.pid"
 
-usage () {
-cat <<END
-Usage: $0 [-h]
-          [-f FRAME_RATE] [-p NUM_PIXELS ] OUT_FILE
-   -h: display this help message and exit.
-   -f: set video framerate.
-   -p: set border pixel of the selected window.
-
-   OUT_FILE: output file.
-END
-   exit 1
-}
-
-die () {
-   printf '%s: %s.\n' "$0" "$*" >&2
-   exit 1
-}
+mkdir -p "$out_dir"
 
 requires () {
-   {
-      for cmd in "$@" ; do
-         command -v "$cmd" || die "$cmd: command not found"
-      done
-   } >/dev/null
-}
-
-is_digit () {
-   expr "$2" : '[0-9]\+$' >/dev/null || die "'$1' must be a digit"
-}
-
-parse_args () {
-
-   while test $# -gt 0 ; do
-      case $1 in
-         -h)
-            usage
-            ;;
-         -f)
-            test $# -lt 2 && usage
-            is_digit framerate "$2"
-            frame_rate=$2
-            ;;
-         -p)
-            test $# -lt 2 && usage
-            is_digit "border_pixel" "$2"
-            pixel_border=$2
-            ;;
-         -*)
-            die "Unknown option \`$1'"
-            ;;
-          *)
-            test $# -gt 1 && usage
-            out_file=$1
-            ;;
-      esac
-      shift 2
-   done
-
-   if test -z "$out_file" ; then
-      die "You must set an output file"
-      usage
-   fi
-
-   out_dir=${out_file%/*}
-
-   mkdir -p "$out_dir" || exit 1
-   test -w "$out_dir"  || die "cannot write to \`$out_dir'"
+   for cmd in "$@" ; do
+      command -v "$cmd" || die "$cmd: command not found"
+   done >/dev/null
 }
 
 record () {
@@ -96,21 +36,29 @@ record () {
       '
    )
 
-   eval ffmpeg                   \
-         -hide_banner             \
-         -f x11grab                \
-         -framerate $frame_rate     \
-         $ff_opts                    \
-         -pix_fmt rgba                \
-         -qp 0                         \
-         -preset ultrafast              \
-         -y "'$out_file'"
+   ffmpeg                   \
+    -hide_banner             \
+    -f x11grab                \
+    -framerate $frame_rate     \
+    $ff_opts                    \
+    -pix_fmt rgba                \
+    -qp 0                         \
+    -preset ultrafast              \
+    -y "$out_file" &
+
+   printf $! >"$pid_file"
+   waitpid $!
 }
 
 main () {
-   requires xwininfo ffmpeg herbe
-   parse_args "$@"
-   record
+   if test -s "$pid_file"    \
+   && pid=$(cat "$pid_file")  \
+   && test -d "/proc/$pid" ; then
+      kill -TERM "$pid"
+   else
+      requires xwininfo ffmpeg herbe
+      record
+   fi
 }
 
 main "$@"
