fix issues with premotes, add npm-install(for LS installation)

diff --git a/premotes b/premotes
--- a/premotes
+++ b/premotes
@@ -1,28 +1,54 @@
 #!/usr/bin/env sh
-
-putokenhere()
-{
-	echo "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"
-}
-
+# private script use to push projects to all remote
+# repositories (codeberg, gitlab, github)
 push()
 {
-	local lbranch='master'
-	local rbranch='master'
-	case $# in
-	1) lbranch="$1" ;;
-	2) lbranch="$1" && rbranch="$2" ;;
-	*) :;;
-	esac
+	local lbranch="${1:-master}"
+	local rbranch="${2:-master}"
+	# assume local project name is the same as that of 
+	# remote repository
 	local cwd="$(basename $PWD)"
-	for i in $remote1 $remote2 $remote2; do
-		printf "Preparing to push local branch to %s/%s\n" $i $cwd
-		git push "${i}/${cwd}" "${lbranch}:${rbranch}"
+	for i in $remote1 $remote2 $remote3
+	do
+		read -p "push on $i(y/n)?" answer
+		if [ "$answer" = y ] || [ "$answer" = Y ]
+		then
+			printf "Preparing to push local branch to %s/%s\n" $i $cwd
+			git push "${i}/${cwd}.git" "${lbranch}:${rbranch}"
+		fi
 	done
 }
 
-remote1="https://$(putokenhere)@github.com/tcheukueppo"
-remote2='https://codeberg.org/tcheukueppo'
-remote3='https://gitlab.org/tcheukueppo'
+push_all()
+{
+	local answer
+	local checkrepo='false'
+	for i in *
+	do
+		if [ -d "$i" ] && [ -d "$i/.git" ]
+		then
+			checkrepo='true'
+			read -p  "push on $i(y/n)?" answer
+			[ "$answer" = y ] || [ "$answer" = Y ] && cd "$i" && push && cd -
+		fi
+	done
+	$(echo $checkrepo) || printf "no repositories found here\n" >&2
+}
 
-push
+xyz()
+{
+	echo "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"
+}
+
+remote1="https://$(xyz)@github.com/tcheukueppo"
+remote2='https://codeberg.org/tcheukueppo'
+remote3='https://gitlab.com/tcheukueppo'
+
+exitcode=0
+case $# in
+0)	push ;;
+1)	[ "$1" = 'all' ] && push_all || exitcode=1 ;;
+2)	push "$1" "$2" ;;
+*)	exitcode=1 ;;
+esac
+[ $exitcode = 1 ] && printf "Invalid arguments\n" >&2
