fix indentation issues and delete unneeded files

diff --git a/bin/linux/stamina b/bin/linux/stamina
--- a/bin/linux/stamina
+++ b/bin/linux/stamina
@@ -1,31 +1,31 @@
-#!/usr/bin/env sh
+#!/bin/sh
 #
 # A script which provides a point to point connection to
 # a USB modem(ex: /dev/ttyUSB*, ...). its dependencies are:
-#	usb_modeswitch, ModemManager, NetworkManager, systemd
+#   usb_modeswitch, ModemManager, NetworkManager, systemd
 #
 #          From: https://codeberg.org@tcheukueppo/scripts.git
 #          Author: kueppo
 
-if test $(uname) != Linux; then
-  echo "${0#./} should be run on a linux system" >&2
-  exit 1
-fi
-if test $(id -u) -ne 0; then
-  echo "root permission needed" >&2
+if test "$(uname)" != Linux ; then
+  printf "%s: should be run on a linux system\n" "$0" >&2
   exit 1
 fi
 
-null='&>/dev/null' && export null
+if test "$(id -u)" -ne 0 ; then
+  printf "%s: root permission needed\n" "$0" >&2
+  exit 1
+fi
+
+null='>/dev/null 2>&1'
 
 usage() {
-cat<<EOF
+cat<<EOF >&2
 Usage: stamina [OPTIONS]... APN
 establishes a connection to a usb modem, modems
 of the type /dev/ttyUSB*, /dev/ttyS*, etc. stamina
 takes as mandatory argument the access point name
 which depends on your service provider.
-	echo
   -k, --kill  delete the network manager connection
               called "stamina" which was created
               when the usb modem was first plug-in.
@@ -37,21 +37,22 @@ check() {
 
    # to switch to from a storage device to a modem
    # send bulk message to the device with usb_modeswitch
-   echo "warn: mode switch the usb device(usb_modeswitch)"
-   printf 'checking dependencies ...'
+   printf 'warn: mode switch the usb device(usb_modeswitch)\n'
+   printf 'checking dependencies ...\n'
    command -v usb_modeswitch >/dev/null || toins="usb_modeswitch"
    command -v ModemManager >/dev/null || toins="ModemManger${toins:+, }${toins}"
    command -v NetworkManager >/dev/null || toins="NetworkManager${toins:+, }${toins}"
-   if test -n "$toins"; then
-      echo failed
-      if echo $toins | fgrep -q ','; then
-	 printf '%s and %s are needed\n' "${toins%,*}" "${toins##* }"
+   if test -n "$toins" ; then
+      printf failed
+      if printf '%s\n' "$toins" | fgrep -q ',' ; then
+         printf '%s and %s are needed\n' "${toins%,*}" "${toins##* }"
       else
-	 printf '%s is needed\n' "${toins}"
+         printf '%s is needed\n' "${toins}"
       fi
       return 1
    fi
-   echo ok
+   printf ok
+
    return 0
 }
 
@@ -59,81 +60,81 @@ servck() {
    local excode=0
 
    printf 'enabling ModemManager service ...'
-   if ! eval systemctl enable ModemManager ${null}; then
-      echo failed
-      ((excode++))
+   if ! eval systemctl enable ModemManager ${null} ; then
+      printf failed
+      excode=$(($excode + 1))
    fi
-   echo ok
+   printf ok
    printf 'starting ModemManger service ...'
-   if ! eval systemctl start ModemManager ${null}; then
-      echo failed
-      ((excode++))
+   if ! eval systemctl start ModemManager ${null} ; then
+      printf failed
+      excode=$(($excode + 1))
    fi
-   echo ok
+   printf ok
    printf 'enabling NetworkManager service ...'
-   if ! eval systemctl enable NetworkManager ${null}; then
-      echo failed
-      ((excode++))
+   if ! eval systemctl enable NetworkManager ${null} ; then
+      printf failed
+      excode=$(($excode + 1))
    fi
-   echo ok
+   printf ok
    printf 'starting NetworkManager service ...'
-   if ! eval systemctl restart NetworkManager ${null}; then
-      echo failed
-      ((excode++))
+   if ! eval systemctl restart NetworkManager ${null} ; then
+      printf failed
+      excode=$(($excode + 1))
    fi
-   echo ok
-   test "$excode" -eq 0 && return 0 || return 1
+   printf ok
+   test $excode -ne 0 && return 1
 }
 
 pppcon() {
-   local pport
-   local timeout=0
+   local pport='' timeout=0
 
-   printf 'listening to usb modems ...'
+   printf 'listening to usb modems ...\n'
    while test "$(mmcli -L)" = "No modems were found"; do
       test $timeout = 8 && break
       sleep 4
-      ((timeout++))
+      timeout=$(($timeout + 1))
    done
-   test $timeout -lt 8 && echo ok || { echo failed; return 1; }
+   test $timeout -lt 8 && printf ok || { printf failed; return 1; }
    # get modem index
    index="$(mmcli -L | cut -d/ -f6 | cut -d ' ' -f1)"
-   if ! echo "$index" | grep -q '[0-9]\{1,\}'; then
-      echo 'could not get modem index' >&2
+   if ! printf '%d\n' "$index" | grep -q '[0-9]\{1,\}' ; then
+      printf 'could not get modem index\n' >&2
       return 1
    fi
    # create a persistent connection with networkmanager
-   if nmcli connection show | grep -q '^Stamina '; then
+   if nmcli connection show 2>/dev/null | grep -q '^Stamina ' ; then
       wmsg() {
-	 echo 'warning: this script should be run once, it creates'
-	 echo 'a persistent connection to a usb modem by creating'
-	 echo 'an active connection with NetworkManager so run'
-	 echo '`stamina -k` do delete the NetworkManager active'
-	 echo 'connection.'
+         printf 'warning: this script should be run once, it creates\n'
+         printf 'a persistent connection to a usb modem by creating\n'
+         printf 'an active connection with NetworkManager so run\n'
+         printf '`stamina -k` do delete the NetworkManager active\n'
+         printf 'connection.\n'
       }
-      wmsg
+      wmsg >&2
       nmcli radio wwan on
       return 1
    fi
+
    pport="$(mmcli -m $index | fgrep 'primary port' | cut -d: -f2)"
    pport=${pport## }
-   if test -c "/dev/$pport"; then
+   if test -c "/dev/$pport" ; then
       nmcli radio wwan on
       nmcli connection add type gsm ifname "$pport" con-name "Stamina" apn "$1"
-      test $? -eq 0 && printf "usb modem connection succeeded"
+      test $? -eq 0 && printf 'usb modem connection succeeded\n'
    fi
    return 0
 }
 
 kilcon() {
    local gguid
-   if ! nmcli connection show | grep -q '^Stamina '; then
-      echo 'no connection found' >&2
+   if ! nmcli connection show | grep -q '^Stamina ' ; then
+      printf 'no connection found\n' >&2
       return 1
    fi
    printf 'attempting to delete the connection ...'
    gguid=$(nmcli connection show | grep '^Stamina ' | sed -n 's/^[^ ]\+ \+\([^ ]\+\).\+/\1/p')
-   nmcli connection delete "$gguid"  && echo ok || echo failed
+   nmcli connection delete "$gguid"  && printf ok || printf failed
    return 0
 }
 
@@ -141,15 +142,15 @@ stamina() {
    case $# in
       0) usage >&2 ;;
       1)
-	 case $1 in
-	    -k|--kill) kilcon ;;
-	    -h|--help) usage ;;
-	    *) check >&2 || exit 1
-	       printf 'connecting to a usb modem with apn "%s"\n' "$1"
-	       servck || return 1
-	       pppcon "$1" || return 1 ;;
-	 esac ;;
-      *) echo 'invalid number of arguments' >&2 ;;
+       case $1 in
+          -k|--kill) kilcon ;;
+          -h|--help) usage ;;
+          *) check >&2 || exit 1
+             printf 'connecting to a usb modem with apn "%s"\n' "$1"
+             servck || return 1
+             pppcon "$1" || return 1 ;;
+       esac ;;
+      *) printf 'invalid number of arguments\n' >&2 ;;
    esac
    return 0
 }
