refine viper

diff --git a/record/viper b/record/viper
--- a/record/viper
+++ b/record/viper
@@ -1,35 +1,53 @@
 #!/bin/sh
 
+vpid="$HOME/.viper.pid"
+
 start_viper() {
-	path="$1"
+	local path="$1"
 
-	[ -e "$path" ] && { printf "%s already exist in file system\n" "$path"; return; }
+	if [ -e "$path" ] 
+	then
+		printf "'%s' already exist in file system\n" "$path" >&2
+		return 1
+	fi
  
-	> "$path" 1>/dev/null 2>&1 && rm -f "$path" || { printf "cannot write to '%s'\n", "$1"; return; }
+	if >"$path" >/dev/null 2>&1
+	then
+		rm -f "$path" 
+	else
+		printf "cannot write to '%s'\n" "$path"
+		return 1
+	fi
 
+	test -f "$vpid" && kill -9 `cat "$vpid"` >/dev/null 2>&1
 	ffmpeg -video_size 1600x900 \
-	       -framerate 100        \
-		   -f x11grab           \
-		   -i :0.0+0,0          \
-		   -f pulse             \
+	       -framerate 100 \
+		   -f x11grab \
+		   -i :0.0+0,0 \
+		   -f pulse \
 		   -i alsa_output.pci-0000_00_1b.0.analog-stereo.monitor \
-		   -ac 2                \
+		   -ac 2 \
 		   "$path" >/dev/null 2>&1 &
 
-	[ -e /tmp/ffmpeg/record ] && kill `cat /tmp/ffmpeg_record` >/dev/null 2>&1
-	printf "%s" "$!" > /tmp/ffmpeg_record
+	printf "$!" >"$vpid"
 }
 
 kill_viper() {
-	kill `cat /tmp/ffmpeg_record` >/dev/null 2>&1
+	if [ -f "$vpid" ]
+	then
+		kill -9 `cat "$vpid"`
+		rm -rf "$vpid"
+	fi
 }
 
 usage() {
-	printf "viper start /path/to/output|stop\n";
+	printf "usage:\n"
+	printf "  viper start /path/to/output.ext\n";
+	printf "  viper stop\n"
 }
 
 case $# in
-	1) [ "$1" == stop  ] && kill_viper || usage ;;
-	2) [ "$1" == start ] && start_viper "$2" ;;
+	1) test "$1" = stop  && kill_viper || usage ;;
+	2) test "$1" = start && start_viper "$2" ;;
 	*) usage ;;
 esac
