fixed some issues on stamina

diff --git a/Linux/stamina b/Linux/stamina
--- a/Linux/stamina
+++ b/Linux/stamina
@@ -16,6 +16,8 @@ if test $(id -u) -ne 0; then
 	exit 1
 fi
 
+declare -x null='&>/dev/null'
+
 usage() {
 cat<<EOF
 Usage: stamina [OPTIONS]... APN
@@ -33,48 +35,58 @@ EOF
 check() {
 	local toins=''
 
+	# to switch to from a storage device to a modem
+	# send bulk message to the device with usb_modeswitch
+	echo "warn: mode switch the usb device(usb_modeswitch)"
 	printf 'checking dependencies ...'
-	if command -v usb_modeswitch; then
-		echo "warn: mode switch the usb device(usb_modeswitch)"
-	else
-		toins="usb_modeswitch"
+	command -v usb_modeswitch >/dev/null || toins="usb_modeswitch"
+	command -v ModemManager >/dev/null || toins="ModemManger${toins:+, }${toins}"
+	command -v NetworkManager >/dev/null || toins="NetworkManager${toins:+, }${toins}"
+	if test -n "$toins"; then
+		echo failed
+		if grep -q ',' <(echo $toins); then
+			printf '%s and %s are needed\n' "${toins%,*}" "${toins##* }"
+		else
+			printf '%s is needed\n' "${toins}"
+		fi
+		return 1
 	fi
-	command -v ModemManager || toins="ModemManger${toins:+, }${toins}"
-	command -v NetworkManager || toins="NetworkManager${toins:+, }${toins}"
-
-	test x"$toins" = x"" && echo ok || echo failed
-	if grep -q ',' <(echo $toins); then
-		printf '%s and %s are needed\n' "${toins%,*}" "${toins##* }"
-	else
-		printf '%s is needed\n' "${toins}"
-	fi
-	return 1
+	echo ok
+	return 0
 }
 
 servck() {
-	local ecode=0
+	local excode=0
 
-	if ! systemctl is-enabled ModemManager &>/dev/null; then
-		printf 'enabling ModemManager service ...'
-		systemctl enabled ModemManager && echo ok || echo failed
-		((ecode++))
+	printf 'enabling ModemManager service ...'
+	if ! eval systemctl enable ModemManager ${null}; then
+		echo failed
+		((excode++))
 	fi
-	if ! systemctl is-active ModemManager &>/dev/null; then
-		printf 'starting ModemManger service ...'
-		systemctl start ModemManager && echo ok || echo failed
-		((ecode++))
+	echo ok
+	printf 'starting ModemManger service ...'
+	if ! eval systemctl start ModemManager ${null}; then
+		echo failed
+		((excode++))
 	fi
-	if ! systemctl is-enabled NetworkManager &>/dev/null; then
-		printf 'enabling NetworkManager service ...'
-		systemctl enabled NetworkManager && echo ok || echo failed
-		((ecode++))
+	echo ok
+	printf 'enabling NetworkManager service ...'
+	if ! eval systemctl enable NetworkManager ${null}; then
+		echo failed
+		((excode++))
 	fi
+	echo ok
 	printf 'starting NetworkManager service ...'
-	systemctl restart NetworkManager && echo ok || echo failed
-	test $ecode -gt 0 && return 1
+	if ! eval systemctl restart NetworkManager ${null}; then
+		echo failed
+		((excode++))
+	fi
+	echo ok
+	test "$excode" -eq 0 && return 0 || return 1
 }
 
 pppcon() {
+	local pport
 	local timeout=0
 
 	printf 'listening to usb modems ...'
@@ -83,10 +95,10 @@ pppcon() {
 		sleep 4
 		((timeout++))
 	done
-	test $timeout = 8 && echo ok || echo failed && return 1
+	test $timeout -lt 8 && echo ok || { echo failed; return 1; }
 	# get modem index
 	index="$(mmcli -L | cut -d/ -f6 | cut -d ' ' -f1)"
-	if grep -q '[0-9]\{1,\}' <(echo "$index"); then
+	if ! grep -q '[0-9]\{1,\}' <(echo "$index"); then
 		echo 'could not get modem index' >&2
 		return 1
 	fi
@@ -104,41 +116,44 @@ pppcon() {
 		return 1
 	fi
 	pport="$(mmcli -m $index | fgrep 'primary port' | cut -d: -f2)"
+	pport=${pport## }
 	if test -c "/dev/$pport"; then
 		nmcli radio wwan on
-		nmcli connection add type gsm ifname "$pport" con-name "Stamina" apn '$1'
+		nmcli connection add type gsm ifname "$pport" con-name "Stamina" apn "$1"
 		test $? -eq 0 && printf "usb modem connection succeeded"
 	fi
 	return 0
 }
 
 kilcon() {
+	local gguid
+
 	if ! nmcli connection show | grep -q '^Stamina '; then
-		echo 'connection not found' >&2
+		echo 'no connection found' >&2
 		return 1
 	fi
 	printf 'attempting to delete the connection ...'
 	gguid=$(nmcli connection show | grep '^Stamina ' | \
 		sed -n 's/^[^ ]\+ \+\([^ ]\+\).\+/\1/p')
-	nmcli connection delete "$gguid" && echo ok || echo failed
+	eval nmcli connection delete "$gguid" ${null} && echo ok || echo failed
 	return 0
 }
 
 stamina() {
-	check >&2 || exit 1
 	case $# in
-	0)
-		usage >&2
+	0)	usage >&2
 		;;
-	1)
-		if test "$1" = '-k' || test "$1" = '--kill'; then kilcon; else
+	1)	case $1 in
+		-k|--kill)
+			kilcon ;;
+		-h|--help)
+			usage ;;
+		*)	check >&2 || exit 1
 			printf 'connecting to a usb modem with apn "%s"\n' "$1"
 			servck || return 1
-			pppcon "$1" || return 1
-		fi
-		;;
-	*)
-		echo invalid number of arguments >&2
+			pppcon "$1" || return 1 ;;
+		esac ;;
+	*)	echo 'invalid number of arguments' >&2
 		;;
 	esac
 	return 0
