now able to use gcreate to create repositories at codeberg gitlab and github.

diff --git a/git-help/gcreate b/git-help/gcreate
--- a/git-help/gcreate
+++ b/git-help/gcreate
@@ -1,19 +1,24 @@
 #!/bin/sh
 
 access=false
+program="${0%%*/}"
 
 usage() { printf "%s\n" "gcreate [-p] -t ACCESS_TOKEN name -n repo_name"; }
-die  () { printf "%s\n" "$1"; exit 1; }
+die  () { printf "%s\n" "$*"; exit 1; }
 
 create_reposit() {
 
-	if expr $name : '[^ ]*' >/dev/null
+	echo "name is $name"
+	if [ `expr "$name" : '\([^ ]*\)'` == "$name" ]
 	then
+
+		tok="$HOME/.local/bin/tok"
+		test -x "$tok" || die "$program: either tok isn't executable or is not found"
 		## create github repository
 		(
-			curl                                              \
-				--request POST                                \
-				--header "Authorization: token $(tok github)" \
+			curl                                               \
+				--request POST                                 \
+				--header "Authorization: token $($tok github)" \
 				--data '
 					{ 
 					  "name": "'$name'",
@@ -25,43 +30,40 @@ create_reposit() {
 
 		## create gitlab repository
 		(
-			curl 
-				--request POST                            \
-				--header "PRIVATE-TOKEN: $(tok gitlab)"   \
-				--header "Content-Type: application/json" \
+			curl                                           \
+				--request POST                             \
+				--header "PRIVATE-TOKEN: $($tok gitlab)"   \
+				--header "Content-Type: application/json"  \
 				--data '
 					{
 					  "name": "'$name'",
 					  "initialize_with_readme": "false"
 					}
-				'                                        \
-				--url 'https://gitlab.example.com/api/v4/projects/'
+				'                                          \
+				--url 'https://gitlab.com/api/v4/projects/'
 		) >/dev/null 2>&1
 
 		## create codeberg repository
 		(
-			curl
-				--request POST                                  \
-				--header "Authorization: token $(tok codeberg)" \
-				--header "Content-Type: application/json"       \
-				--date '
+			curl                                                 \
+				--request POST                                   \
+				--header "Authorization: token $($tok codeberg)" \
+				--header "Content-Type: application/json"        \
+				--header "accept: application/json"              \
+				--data '
 					{
-					  "auto_init": true,
 					  "default_branch": "master",
-					  "description": "'$descript'",
-					  "gitignores": "string",
-					  "issue_labels": "string",
+					  "description": "'"$descript"'",
 					  "license": "GPL3",
 					  "name": "'$name'",
 					  "private": '$access',
-					  "readme": "string",
 					  "template": true,
 					  "trust_model": "default"
 					}
 				'                                               \
-				--url 'https://codeberg.org/api/v1/user/repos'
-		)
-	else die "'$name' is an invalid repository name"; fi
+				--url 'https://codeberg.org/api/v1/user/repos'  \
+		) >/dev/null 2>&1
+	else die "$program: '$name' is an invalid repository name"; fi
 }
 
 main() {
@@ -72,16 +74,17 @@ main() {
 			case "$opt" in
 				p)  access=true ;;
 				n)  name=$OPTARG ;;
-				d)  descript=$OPTARG
+				d)  descript=$OPTARG ;;
 				\?) die "unknown '$(eval \$$((OPTIND - 1)))'" ;;
 			esac
 		done
 
 		shift $((OPTIND - 1))
-		test $# -ne 0 && die "invalid options"
+		test $# -ne 0 && die "$program: invalid option count"
 		create_reposit
 
 	else usage; fi
 }
 
+main "$@"
 
diff --git a/git-help/push-star b/git-help/push-star
--- a/git-help/push-star
+++ b/git-help/push-star
@@ -1,23 +1,74 @@
 #!/bin/sh
 
-for i in                                         \
+## useful lines for cronjobs
+## personal: 
 
-	## Personal repositories
-	kst kdwm ksent kslock kfetch kslstatus       \
-	myresources amonia lemonbar-xft herbe        \
-	learn gists ktoolbox svis snvim conky.store  \
-	wfmux farbfeld-utils apriori kdmenu kuttix   \
-	krit weeklychallenge sia sad raku-matrix     \
-	perl-matrix sysutils farbfeld-4              \
+warn() { printf '%s\n' "$*" >&2; }
+die()  { warn "$*"; exit 1; }
 
-	## Orginazational repositories (lisa)
-	lisa lisad paranoid
-do
-	repo="$HOME/projects/$i"
-	if [ -d "$repo/.git" ]; then 
-		# check commit id
-		cd "$repo"
-		
-		git push "https://github.com/tcheukueppo/$i"
-	fi
-done
+project_dir="$HOME/projects"
+program="${0%%*/}"
+
+command -v git >/dev/null || die "$program: git not found"
+command -v tok >/dev/null || die "$program: tok not found"
+
+## Personal repositories
+personal_repo() {
+	for i in                                         \
+
+		kst kdwm ksent kslock kfetch kslstatus       \
+		myresources amonia orange herbe              \
+		learn gists ktoolbox svis snvim conky.store  \
+		wfmux farbfeld-utils apriori kdmenu kuttix   \
+		krit weeklychallenge sia sad raku-matrix     \
+		perl-matrix sysutils farbfeld-4              \
+	do
+		## attempt to create even if it exists
+		command -v gcreate && gcreate -p -n "$i" -d "$i" >/dev/null 2>&1
+
+		repository="$(readlink -f "$project_dir/$i")"
+		if [ ! -d "$repository" ]
+		then
+			[ -w "$repository" ] || continue
+			mkdir "$repository"                   &&
+			git init                              &&
+			echo "## $i" >> README.md             &&
+			git add .                             &&
+			git commit -m "initial commit for $i"
+		else
+			## if already committed then push
+			git status | tail -n1 | grep -qE 'nothing to commit|`' || {
+				printf 'on %s...\n' "$i"
+
+				for j in github.com gitlab.org codeberg.org
+				do
+					link="https://$(tok ${j##.*})@$j/tcheukueppo/$i"
+					printf 'push %s to %s\n' $i $link
+					## push the current branch
+					git push 
+				done; false
+			} && { warn "$i repository is uncommited/not added to the index"; }
+		fi
+	done
+}
+
+## Orginazational repositories (lisa)
+organizational_repo() {
+
+	for_body() {
+		org_name="$1"
+		shift
+		for i in "$@"; do
+			link=""
+		done
+	}
+
+	## organization: lisa
+	for i in lisa lisad; do
+		for_body lisa github.com gitlab.com codeberg.org
+	done
+	## organization: paranoid
+	for i in paranoid; do
+		for_body paranoid github.com gitlab.com codeberg.org
+	done
+}
