rewrote gcreate

diff --git a/git-help/gcreate b/git-help/gcreate
--- a/git-help/gcreate
+++ b/git-help/gcreate
@@ -1,89 +1,68 @@
 #!/bin/sh
 
-program="${0##*/}"
+readonly program="${0##*/}"
 
 # default visibility of the project
 access=false
 
 main() {
-	command -v tok >/dev/null || die "$program: tok not found"
-
-	if (test $# -ge 4 && test $# -le 5)
+	if [ $# -eq 1 -a \( "$1" = -h -o "$1" = --help \) ]
 	then
-		while getopts :pn:d: opt
-		do
-			case "$opt" in
-				p)  access=true      ;;
-				n)  name=$OPTARG     ;;
-				d)  descript=$OPTARG ;;
-				\?) die "unknown '$(eval \$$((OPTIND - 1)))'" ;;
-			esac
-		done
+		usage; return
+	elif [ $# -lt 6 ]
+	then
+		usage && die "invalid number of arguments"
+	fi
 
-		shift `expr $OPTIND - 1`
-		test $# -ne 0 && die "$program: invalid option count"
-
-		create_repository
-	else usage; fi
+	while [ $# -ne 0 ]; do
+		case $1 in
+			-p) access=true; shift ;;
+			-r) remote=$2; shift 2 ;;
+			-n) name=$2; shift 2   ;;
+			-d) descript=$2; shift 2 ;;
+			 *) usage; exit 1        ;;
+		esac
+	done
+	create_repo
 }
 
-usage() { printf "gcreate [-p] -d description -n repo_name\n"; }
-die  () { printf "%s\n" "$*"; exit 1; }
+die() { printf "%s: %s\n" "$pname" "$*"; exit 1; }
 
-create_repository() {
-
-	if [ `expr "$name" : '\([^ ]*\)'` = "$name" ]
-	then
-		## create github repository
-		(
-			curl                                               \
-				--request POST                                 \
-				--header "Authorization: token $(tok github)"  \
-				--data '
-					{ 
-					  "name": "'$name'",
-					  "private": '$access'
-					}
-				'                                              \
-				--url 'https://api.github.com/user/repos'
-		) >/dev/null 2>&1
-
-		## create gitlab repository
-		(
-			curl                                          \
-				--request POST                            \
-				--header "PRIVATE-TOKEN: $(tok gitlab)"   \
-				--header "Content-Type: application/json" \
-				--data '
-					{
-					  "name": "'$name'",
-					  "initialize_with_readme": "false"
-					}
-				'                                         \
-				--url 'https://gitlab.com/api/v4/projects/'
-		) >/dev/null 2>&1
-
-		## create codeberg repository
-		(
-			curl                                                \
-				--request POST                                  \
-				--header "Authorization: token $(tok codeberg)" \
-				--header "Content-Type: application/json"       \
-				--header "accept: application/json"             \
-				--data '
-					{
-					  "default_branch": "master",
-					  "description": "'"$descript"'",
-					  "license": "GPL3",
-					  "name": "'$name'",
-					  "private": '$access',
-					  "template": true,
-					  "trust_model": "default"
-					}
-				'                                               \
-				--url 'https://codeberg.org/api/v1/user/repos'  \
-		) >/dev/null 2>&1
-	else die "$program: '$name' is an invalid repository name"; fi
+usage() {
+	printf "usage:"
+	printf "     gcreate [-p] -r <gitlab.com|codeberg.org|...> -n <repo_name> -d <description>"
+	printf "     gcreate --help|-h"
 }
 
+create_repo() {
+
+	header=; data=; api_url=
+	service=${name%.*}
+
+	if [ "$service" = codeberg ]
+	then
+		api_url="https://codeberg.org/api/v1/user/repos"
+		header="Authorization: token $(tok github)"
+		data='{"default_branch":"master","description":"'"$descript"'","license":"GPL3","name":"'$name'","private":'$access',"template":true,"trust_model":"default"}'                                               \
+	elif [ "$service" = github ]
+	then
+		api_url="https://api.github.com/user/repos"
+		header="Authorization: token $(tok codeberg)"
+		data='{"name":"'$name'","private":'$access'}'
+	elif [ "$service" = gitlab ]
+	then
+		api_url="https://gitlab.com/api/v4/projects/"
+		header="PRIVATE-TOKEN: $(tok gitlab)"
+		data='{"name":"'$name'","initialize_with_readme":"false"}'
+	else
+		die "cannot handle token for such service"
+	fi
+
+	curl --request POST       \
+	     --header  "$header"  \
+	     --data    "$data"    \
+	     --url     "$api_url" >/dev/null 2>&1
+}
+
+command -v tok >/dev/null || die "$pname: tok not found"
 main "$@"
