changed == to = in gcreate

diff --git a/git-help/gcreate b/git-help/gcreate
--- a/git-help/gcreate
+++ b/git-help/gcreate
@@ -1,55 +1,75 @@
 #!/bin/sh
 
-access=false
-program="${0%%*/}"
+program="${0##*/}"
 
-usage() { printf "%s\n" "gcreate [-p] -t ACCESS_TOKEN name -n repo_name"; }
+# default visibility of the project
+access=false
+
+main() {
+	command -v tok >/dev/null || die "$program: tok not found"
+
+	if (test $# -ge 4 && test $# -le 5)
+	then
+		while getopts :pn:d: opt
+		do
+			case "$opt" in
+				p)  access=true      ;;
+				n)  name=$OPTARG     ;;
+				d)  descript=$OPTARG ;;
+				\?) die "unknown '$(eval \$$((OPTIND - 1)))'" ;;
+			esac
+		done
+
+		shift `expr $OPTIND - 1`
+		test $# -ne 0 && die "$program: invalid option count"
+
+		create_repository
+	else usage; fi
+}
+
+usage() { printf "gcreate [-p] -d description -n repo_name\n"; }
 die  () { printf "%s\n" "$*"; exit 1; }
 
-create_reposit() {
+create_repository() {
 
-	echo "name is $name"
-	if [ `expr "$name" : '\([^ ]*\)'` == "$name" ]
+	if [ `expr "$name" : '\([^ ]*\)'` = "$name" ]
 	then
-
-		tok="$HOME/.local/bin/tok"
-		test -x "$tok" || die "$program: either tok isn't executable or is not found"
 		## create github repository
 		(
 			curl                                               \
 				--request POST                                 \
-				--header "Authorization: token $($tok github)" \
+				--header "Authorization: token $(tok github)"  \
 				--data '
 					{ 
 					  "name": "'$name'",
 					  "private": '$access'
 					}
-				'                                            \
+				'                                              \
 				--url 'https://api.github.com/user/repos'
 		) >/dev/null 2>&1
 
 		## create gitlab repository
 		(
-			curl                                           \
-				--request POST                             \
-				--header "PRIVATE-TOKEN: $($tok gitlab)"   \
-				--header "Content-Type: application/json"  \
+			curl                                          \
+				--request POST                            \
+				--header "PRIVATE-TOKEN: $(tok gitlab)"   \
+				--header "Content-Type: application/json" \
 				--data '
 					{
 					  "name": "'$name'",
 					  "initialize_with_readme": "false"
 					}
-				'                                          \
+				'                                         \
 				--url 'https://gitlab.com/api/v4/projects/'
 		) >/dev/null 2>&1
 
 		## create codeberg repository
 		(
-			curl                                                 \
-				--request POST                                   \
-				--header "Authorization: token $($tok codeberg)" \
-				--header "Content-Type: application/json"        \
-				--header "accept: application/json"              \
+			curl                                                \
+				--request POST                                  \
+				--header "Authorization: token $(tok codeberg)" \
+				--header "Content-Type: application/json"       \
+				--header "accept: application/json"             \
 				--data '
 					{
 					  "default_branch": "master",
@@ -66,25 +86,4 @@ create_reposit() {
 	else die "$program: '$name' is an invalid repository name"; fi
 }
 
-main() {
-	if (test $# -ge 4 && test $# -le 5)
-	then
-		while getopts :pn:d: opt
-		do
-			case "$opt" in
-				p)  access=true ;;
-				n)  name=$OPTARG ;;
-				d)  descript=$OPTARG ;;
-				\?) die "unknown '$(eval \$$((OPTIND - 1)))'" ;;
-			esac
-		done
-
-		shift $((OPTIND - 1))
-		test $# -ne 0 && die "$program: invalid option count"
-		create_reposit
-
-	else usage; fi
-}
-
 main "$@"
-
diff --git a/git-help/push-star b/git-help/push-star
--- a/git-help/push-star
+++ b/git-help/push-star
@@ -9,11 +9,11 @@ main() {
 	##<<<<< cron should add new repositories here
 	personal_repo=$(cat<<-EOF
 		tcheukueppo
-		kst kdwm ksent kslock kfetch kslstatus
-		myresources amonia orangebar herbe
-		learn gists ktoolbox svis snvim conky.store
 		wfmux farbfeld-utils apriori kdmenu kuttix
+		learn gists ktoolbox svis snvim conky.store
+		kst kdwm ksent kslock kfetch kslstatus
 		krit weeklychallenge sia sad raku-matrix
+		myresources amonia orangebar herbe
 		perl-matrix sysutils farbfeld-4
 	EOF
 	)
@@ -74,20 +74,19 @@ can_connect() {
 
 ## 100% sure these variables a words :)
 sub_push() {
-	name=$1; domain=$2; repo=$3
 	private=
+	name=$1; domain=$2; repo=$3
 
 	olink="https://$domain/$name/$repo"
 	printf 'push %s to %s\n' $repo $olink
 	if can_connect $domain; then
 		[ "$domain" = 'gitlab.com' ] && private=create:
 		private="${private}$(tok ${domain%%.*})"
-		git push "$(printf '%s' "$olink" | sed -e "s#\(^https://\)#\1$private@#")" || warn "failed.'"
+		git push "$(printf '%s' "$olink" | sed -e "s#\(^https://\)#\1$private@#")" || warn "failed to push $repo to $olink."
 	fi
 }
 
 push_to_personal_repository() {
-
 	project_dir="$HOME/projects"
 	username="$(printf '%s' "$personal_repo" | sed -n '1p')"
 	personal_list="$(printf '%s' "$personal_repo" | awk 'NR > 1{print $0}')"
@@ -100,7 +99,7 @@ push_to_personal_repository() {
 		cd "$repository"
 
 		## attempt to create repo even if it exists, which kinda slow things up but...
-		gcreate -p -n "$i" -d "$i" >/dev/null 2>&1
+		gcreate -p -n "$i" -d "$i" #>/dev/null 2>&1
 
 		if git status | tail -n1 | grep -qE 'nothing to commit'
 		then
@@ -111,8 +110,8 @@ push_to_personal_repository() {
 }
 
 push_to_organizational_repository() {
-
 	project_dir="$HOME/projects"
+
 	printf '%s' "$organisation_repo" | while read org_repo
 	do
 		org_name="$(printf '%s' "$org_repo" | awk -F[':'] '{print $0}')"
