same as previous commit + git-cron: to add newly create repositories in push-star source

diff --git a/git-help/push-star b/git-help/push-star
--- a/git-help/push-star
+++ b/git-help/push-star
@@ -51,12 +51,22 @@ main() {
 warn()  { printf '%s\n' "$*" >&2; return 1; }
 die ()  { warn "$*"; exit 1; }
 
+sub_push() {
+	name=$1; domain=$2; repo=$3
+
+	printf 'push %s to https://%s/%s/%s/' "$repo" "$domain" "$name" "$repo"
+	private="$([ "$domain" = 'gitlab.com' ] && printf 'create:'; tok ${domain%%.*})"
+	#git push "$(printf '%s' "$olink" | sed -e "s#\(^https://\)#\1$private@#")" || warn "failed.'"
+}
+
 push_to_personal_repository() {
 
+	project_dir="$HOME/projects"
 	username="$(printf '%s' "$personal_repo" | sed -n '1p' | tr -d ':' | tr -d ' ')"
 	personal_list="$(printf '%s' "$personal_repo" | awk 'NR > 1{print $0}')"
 
-	for i in $personal_list; do
+	for i in $personal_list
+	do
 		repository="$(readlink -f "$project_dir/$i")"
 
 		## attempt to create repo even if it exists, which kinda slow things up but...
@@ -64,46 +74,42 @@ push_to_personal_repository() {
 
 		[ -x "$repository" ]      || continue
 		[ -d "$repository/.git" ] || continue
-
 		cd "$repository"
+
 		if git status | tail -n1 | grep -qE 'nothing to commit'
 		then
 			printf 'on %s...\n' "$i"
-			for j in $remote_repo
-			do
-				olink="https://$j/$username/$i"
-				link=`printf '%s' "$olink" | sed -e "s#\(^https://\)#\1$([ "$j" = 'gitlab.com' ] && printf 'create:')$(tok ${j%%.*})@#"`
-				printf 'push %s to %s\n' "$i" "$link"
-				git push "$link" || warn "failed to push $i to '$olink'"
-			done
-		else
-			warn "ignoring '$i'"
-		fi
+			for j in $remote_repo; do sub_push $username $j $i; done
+		else warn "ignoring '$i'"; fi
 	done
 }
 
 push_to_organizational_repository() {
 
+	project_dir="$HOME/projects"
 	printf '%s' "$organisation_repo" | while read org_repo
 	do
-		expr "$org_repo" : '[ \t]*' >/dev/null >&2 && continue
-		org_name="$(printf '%s' "$org_repo" | awk )"
-		org_list="$(printf '%s' "$org_repo" | awk )"
-		for i in $org_list; do
-			for j in $remote_repo
-			do
-				olink="https://$j/$username/$i"
-				link=`printf '%s' "$olink" | sed -e "s#\(^https://\)#\1$([ "$j" = 'gitlab.com' ] && printf 'create:')$(tok ${j%%.*})@#"`
-				printf 'push %s to %s\n' "$i" "$link"
-				git push "$link" || warn "failed to push $i to '$olink'"
-			done
+		expr "$org_repo" : '^[ \t]*$' >/dev/null 2>&1 && continue
+
+		org_name="$(printf '%s' "$org_repo" | awk -F[':'] '{print $0}' | tr -d ' ')"
+		org_list="$(printf '%s' "$org_repo" | awk -F[':'] '{print $1}')"
+		for i in $org_list
+		do
+			repository="$(readlink -f "$project_dir/$i")"
+			[ -x "$repository" ]      || continue
+			[ -d "$repository/.git" ] || continue
+			cd "$repository"
+
+			if git status | tail -n1 | grep -qE 'nothing to commit'
+			then
+				print 'on %s...\n' "$i"
+				for j in $remote_repo; do sub_push $org_name $j $i; done
+			else warn "ignoring '$i'"; fi
 		done
 	done
 }
 
-project_dir="$HOME/projects"
 program="${0%%*/}"
-
 for i in git tok gcreate; do command -v "$i" >/dev/null || die "$program: $i not found"; done
 
 main "$@" > "$HOME/.push-star.log"
