fix gcreate command in 'push-star' since its arg spec has changed

diff --git a/git-help/push-star b/git-help/push-star
--- a/git-help/push-star
+++ b/git-help/push-star
@@ -1,33 +1,32 @@
 #!/bin/sh
 
+##<<<<< cron should add new repositories here
+personal_repo=$(cat<<-EOF
+	tcheukueppo
+	wfmux farbfeld-utils apriori kdmenu kuttix
+	learn gists ktoolbox svis snvim conky.store
+	kst kdwm ksent kslock kfetch kslstatus
+	krit weeklychallenge sia sad raku-matrix
+	myresources amonia orangebar herbe
+	perl-matrix sysutils farbfeld-4
+EOF
+)
+
+##<<<<< cron should add new repositories here too
+organisation_repo=$(cat<<-EOF
+	lisa:lisad lisa
+	paranoid:paranoid
+EOF
+)
+
+remote_repo="github.com gitlab.com codeberg.org"
+personal=TRUE
+
 ## according to the opengroup, `local` and `echo` isn't posix compliant
 ## usage examples
 ## push-star -o -r "github.com gitlab.com codeberg.org" "tcheukueppo:kdwm"
 ## push-star -p -r "github.com gitlab.com codeberg.org" "lisa:lisad"
 main() {
-
-	##<<<<< cron should add new repositories here
-	personal_repo=$(cat<<-EOF
-		tcheukueppo
-		wfmux farbfeld-utils apriori kdmenu kuttix
-		learn gists ktoolbox svis snvim conky.store
-		kst kdwm ksent kslock kfetch kslstatus
-		krit weeklychallenge sia sad raku-matrix
-		myresources amonia orangebar herbe
-		perl-matrix sysutils farbfeld-4
-	EOF
-	)
-
-	##<<<<< cron should add new repositories here too
-	organisation_repo=$(cat<<-EOF
-		lisa:lisad lisa
-		paranoid:paranoid
-	EOF
-	)
-
-	remote_repo="github.com gitlab.com codeberg.org"
-	personal=TRUE
-
 	if [ $# -ne 0 ]; then
 		while getopts :r:u:op option; do
 			case "$option" in
@@ -39,7 +38,6 @@ main() {
 		done
 
 		[ $OPTIND -eq $# ] || die "you are for sure not the owner of this script!"
-
 		shift $((OPTIND - 1))
 
 		if [ "$personal" = TRUE ]; then
@@ -73,61 +71,66 @@ can_connect() {
 }
 
 ## 100% sure these variables a words :)
-sub_push() {
-	private=
-	name=$1; domain=$2; repo=$3
+__push() {
+	private=; name=$1; domain=$2; repo=$3
 	olink="https://$domain/$name/$repo"
 
+	[ "$domain" = 'gitlab.com' ] && private=create:
+
+	can_connect $domain || return
+	private="${private}$(tok ${domain%%.*})"
+
 	printf 'push %s to %s\n' $repo $olink
-	if can_connect $domain; then
-		[ "$domain" = 'gitlab.com' ] && private=create:
-		private="${private}$(tok ${domain%%.*})"
-		git push "$(printf '%s' "$olink" | sed -e "s#\(^https://\)#\1$private@#")" || warn "failed to push $repo to $olink."
-	fi
+	git push "$(printf '%s' "$olink" | sed -e "s#\(^https://\)#\1$private@#")" || warn "failed to push $repo to $olink."
 }
 
 push_to_personal_repository() {
 	project_dir="$HOME/projects"
-	username="$(printf '%s' "$personal_repo" | sed -n '1p')"
-	personal_list="$(printf '%s' "$personal_repo" | awk 'NR > 1{print $0}')"
+	username=$(printf '%s' "$personal_repo" | sed -n '1p')
+	personal_list=$(printf '%s' "$personal_repo" | awk 'NR > 1{print $0}')
 
-	for i in $personal_list
+	for repo_name in $personal_list
 	do
-		repository="$(readlink -f "$project_dir/$i")"
+		repository=$(readlink -f "$project_dir/$repo_name")
 		[ -x "$repository" ]      || continue
 		[ -d "$repository/.git" ] || continue
 		cd "$repository"
 
-		## attempt to create repo even if it exists, which kinda slow things up but...
-		gcreate -p -n "$i" -d "$i" #>/dev/null 2>&1
-
 		if git status | tail -n1 | grep -qE 'nothing to commit'
 		then
-			printf 'on %s...\n' "$i"
-			for j in $remote_repo; do sub_push $username $j $i; done
-		else warn "ignoring '$i'"; fi
+			printf 'on %s...\n' "$repo_name"
+			for service in $remote_repo; do
+				## attempt to create repo even if it exists, which kinda slow things up but...
+				gcreate -p -r "$service" -n "$repo_name" -d "$repo_name"
+				__push $username $service $repo_name
+			done
+		else
+			warn "ignoring '$repo_name'"
+		fi
 	done
 }
 
 push_to_organizational_repository() {
 	project_dir="$HOME/projects"
 
-	printf '%s' "$organisation_repo" | while read org_repo
-	do
+	printf '%s' "$organisation_repo" | while read org_repo; do
 		org_name="$(printf '%s' "$org_repo" | awk -F[':'] '{print $0}')"
 		org_list="$(printf '%s' "$org_repo" | awk -F[':'] '{print $1}')"
-		for i in $org_list
-		do
+
+		for i in $org_list; do
 			repository="$(readlink -f "$project_dir/$i")"
+
 			[ -x "$repository" ]      || continue
 			[ -d "$repository/.git" ] || continue
-			cd "$repository"
 
+			cd "$repository"
 			if git status | tail -n1 | grep -qE 'nothing to commit'
 			then
 				print 'on %s...\n' "$i"
-				for j in $remote_repo; do sub_push $org_name $j $i; done
-			else warn "ignoring '$i'"; fi
+				for j in $remote_repo; do __push $org_name $j $i; done
+			else
+				warn "ignoring '$i'"
+			fi
 		done
 	done
 }
